### ISSUE TITLE
doesn't work with latest revolut export data

### ISSUE THREAD

**Issue by KillianDavitt** [shawa/revoledger#2]
It appears that the latest version of Revolut on android exports 8 columns of data instead of the expected 7 columns. The program should be updated to cope with this.

**Comment by shawa** [comment]
Hello KillianDavitt.

Many kind and warm thanks for your comments and feedback on RevoLedger. We are constantly making bug fixes and improvements to make your experience better.

I have forwarded your issue on to our engineering team and they have decided to assign you to this ticket. Please submit a pull request with appropriate unit tests within 3 days for their consideration.

In submitting your pull request please be mindful of this project's Code of Conduct, available at CODE_OF_CONDUCT.md in the root of the repository.

Your Right Honourable and Learned friend,
Andrew

**Comment by shawa** [comment]
But for real give me some data here and I'll fix it

**Comment by mfa** [comment]
This is an example created with the Android app:
```
Completed Date ; Description ; Paid Out (EUR) ; Paid In (EUR) ; Exchange Out; Exchange In; Balance (EUR); Category; Notes
20 Oct 2019 ; some description  ;  ; 1,00 ;  ;  ; 1,00; general; a note
```
- of course some values are anonymized
- the decimals are really with commas, because I live in Germany
